version: 2.1

defaults:  # 添加了 defaults 根键
  executors:
    ubuntu-executor:
      docker:
        - image: ubuntu:latest
      environment:
        CI: circleci

jobs:
  build:
    # docker:
    #   - image: cimg/python:3.8
    working_directory: ~/project
    parameters:
      owner:
        type: string
        default: "immortalwrt"
      repo:
        type: string
        default: "immortalwrt"
      branch:
        type: string
        default: "openwrt-23.05"

    steps:
      - checkout

      - run:
          name: 安装编译所需的依赖 (Install the software packages required for compilation)
          command: |
            sudo apt update
            sudo apt full-upgrade -y
            sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - run:
          name: Clean up before build
          command: |
            sudo apt-get clean
            sudo rm -rf /var/lib/apt/lists/*
            df -h  # Show disk space usage

      - run:
          name: 克隆 ImmortalWrt 仓库 (Clone ImmortalWrt repo)
          command: |
            git clone --depth=1 --branch << parameters.branch >> https://github.com/<< parameters.owner >>/<< parameters.repo >> ImmortalWrt

      - run:
          name: 复制当前仓库的配置文件到 ImmortalWrt 仓库 (Copy current repo config to ImmortalWrt repo)
          command: |
            cp -f .config diy.sh ImmortalWrt/

      - run:
          name: 运行 diy.sh (Run diy.sh)
          command: |
            cd ImmortalWrt
            chmod +x diy.sh
            ./diy.sh

      - run:
          name: 更新并下载 feeds (Update and download feeds)
          command: |
            cd ImmortalWrt
            ./scripts/feeds update -a && ./scripts/feeds install -a

      - run:
          name: 再次复制当前仓库的配置文件到 ImmortalWrt 仓库 (Copy current repo config to ImmortalWrt repo again)
          command: |
            cp -f .config diy.sh ImmortalWrt/

      - run:
          name: 多线程编译 ImmortalWrt (Build ImmortalWrt multithreading)
          command: |
            cd ImmortalWrt
            if [ $(nproc) -gt 8 ]; then con=$(( $(nproc) / 2 + 3 )); else con=$(nproc); fi
            make defconfig
            make -j$con || make -j1 V=s

      - persist_to_workspace:
          root: ~/project
          paths:
            - ImmortalWrt/bin/targets

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          owner: "immortalwrt"
          repo: "immortalwrt"
          branch: "openwrt-23.05"
